# Generated by Django 2.0.1 on 2018-02-05 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_barcamp_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='barcamp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='api.Barcamp'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='speaker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='api.Speaker'),
        ),
    ]
