# Generated by Django 2.0.1 on 2018-02-05 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180205_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='barcamp',
            new_name='barcamp_id',
        ),
        migrations.RenameField(
            model_name='talk',
            old_name='speaker',
            new_name='speaker_id',
        ),
    ]
