# Generated by Django 2.0.1 on 2018-02-05 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180205_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='barcamp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks_ids', to='api.Barcamp'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='speaker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talks_ids', to='api.Speaker'),
        ),
    ]
