# Generated by Django 2.0.1 on 2018-02-06 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180205_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
