# Generated by Django 2.0.1 on 2018-02-08 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20180208_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='slides',
            field=models.FileField(null=True, upload_to='slides'),
        ),
    ]
